# Execute your favorite apps at launch
exec-once = waybar
#exec-once = hyprpaper
exec-once = dunst

exec-once = swww-daemon --format xrgb
exec-once = variety
# Load configuration from ML4W Hyprland Settings App
exec = ~/.config/ml4w-hyprland-settings/hyprctl.sh
exec-once = wl-paste --type text --watch cliphist store # Stores only text data

exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = systemctl --user start hyprpolkitagent
exec-once = nm-applet
exec-once = blueman-applet
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
