# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
#windowrulev2 = float,class:(mpv)
#windowrulev2 = pin,class:(mpv)
#windowrulev2= move onscreen 95% 5%, class:(mpv)
#windowrulev2 = size 20% 20%,class:mpv
#windowrulev2 = float,class:(smplayer)
#windowrulev2 = pin,class:(smplayer)
#windowrulev2= move onscreen 95% 5%, class:(smplayer)
#windowrulev2 = size 20% 20%,class:(smplayer)
